baseURL = "https://akanom11.github.io/"
languageCode = "es-es"
title = "RincÃ³n de Antonio"

theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true

# Homepage: PresentaciÃ³n personal
[params.profileMode]
  enabled = true
  title = "Sitio de Antonio"
  subtitle = "Espacio personal | Sysadmin, libros, cine, deporte, juegos y pensamientos"
  imageUrl = "images/me.jpg"
  buttons = [
    {name = "ðŸ’» Sysadmin/DevOps", url = "/sysadmin/"},
    {name = "ðŸ“š Blog", url = "/posts/"},
    {name = "ðŸ‘¤ Acerca de", url = "/about/"},
  ]

# MenÃº principal
[[menu.main]]
  name = "Sysadmin"
  url = "/sysadmin/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Acerca"
  url = "/about/"
  weight = 3

# SubmenÃºs Blog (opcional)
[[menu.main]]
  name = "Libros ðŸ“š"
  url = "/posts/libros/"
  parent = "Blog"
  weight = 1

[[menu.main]]
  name = "Juegos ðŸŽ®"
  url = "/posts/juegos/"
  parent = "Blog"
  weight = 2

[[menu.main]]
  name = "Deporte ðŸ¥‹"
  url = "/posts/deporte/"
  parent = "Blog"
  weight = 2

[[menu.main]]
  name = "Cine y series ðŸŽ¬"
  url = "/posts/cine/"
  parent = "Blog"
  weight = 3

[[menu.main]]
  name = "Pensamientos ðŸ’­"
  url = "/posts/pensamientos/"
  parent = "Blog"
  weight = 4

